local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
  
amazon:
  service: S3
  access_key_id: <%= ENV["s3_access_key_id"] %>
  secret_access_key: <%= ENV["s3_secret_access_key"] %>
  bucket: <%= ENV["s3_bucket"] %>
  region: <%= ENV["s3_region"] %>